# 矩阵运算

In [1]:
import numpy as np
import pandas as pd

## 1. numpy 中的矩阵表示与特殊矩阵构建
一般都用数组来创建矩阵，而不用matrix，因为数组计算速度更快。

In [2]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [43]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
# 转置
A.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [5]:
# 对角矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# 返回对角线上元素
np.diag(A)

array([1, 5])

In [23]:
# 以指定对角线创建单位阵
display(np.diag(np.arange(5)))
display(np.diag(np.arange(5),1)) # 对角线上移一位
display(np.diag(np.arange(5),-1)) # 对角线下移一位

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0]])

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0]])

In [20]:
# 创建上三角矩阵（下三角置为0）
display(np.triu(A))
display(np.triu(A,1)) # 上偏移
display(np.triu(A,-1)) # 下偏移

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0, 18, 19],
       [ 0,  0,  0,  0, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  7,  8,  9],
       [ 0,  0,  0, 13, 14],
       [ 0,  0,  0,  0, 19],
       [ 0,  0,  0,  0,  0]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0, 11, 12, 13, 14],
       [ 0,  0, 17, 18, 19],
       [ 0,  0,  0, 23, 24]])

In [24]:
# 创建下三角矩阵
display(np.tril(A))

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0],
       [10, 11, 12,  0,  0],
       [15, 16, 17, 18,  0],
       [20, 21, 22, 23, 24]])

## 2. 矩阵基本运算
- 逐元素相乘

In [34]:
A = np.arange(6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
display(A*A, A+A)

array([[ 0,  1,  4],
       [ 9, 16, 25]])

array([[ 0,  2,  4],
       [ 6,  8, 10]])

- 向量点积：对应位置元素相乘再相加

In [36]:
np.vdot(A,A) # 矩阵必须形状相同

55

- 矩阵乘法:第一个矩阵的列和第二个矩阵的行必须一样

In [39]:
np.dot(A,A.reshape(3,2))

array([[10, 13],
       [28, 40]])

## 3. 矩阵代数运算
linalg就是线性代数（linear algebra）的简写
- 矩阵的迹：对角线上元素之和，矩阵不一定是方阵

In [44]:
B = np.arange(25).reshape(5,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
np.trace(B)

60

In [48]:
C = np.arange(20).reshape(4,5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
np.trace(C) # 0,6,12,18

36

- 矩阵的秩（rank）:可以由其他行/列线性变换得到的行/列不计数，可以为特征选择、奇异值分解等提供帮助

In [49]:
np.linalg.matrix_rank(B)

2

- 矩阵的行列式（det）:必须是方阵，行列式不为0说明矩阵不满秩，矩阵不可逆。行列式是矩阵进行线性变换的伸缩因子。

In [50]:
np.linalg.det(B)

0.0

In [51]:
D= np.array([[1,2],[4,5]])
D

array([[1, 2],
       [4, 5]])

In [52]:
np.linalg.det(D)

-2.9999999999999996

- 矩阵的逆矩阵：必须是方阵，矩阵满秩，行列式不等于0。从方程组求解来讲，若系数构成的矩阵存在逆矩阵，那存在唯一解。

In [56]:
np.linalg.inv(D)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [57]:
np.dot(D,np.linalg.inv(D))

array([[1., 0.],
       [0., 1.]])

## 4. 矩阵方程求解

In [71]:
# AX=B
A = np.array([[20,8],[8,4]])
B = np.array([[28,12]]).T
display(A,B)

array([[20,  8],
       [ 8,  4]])

array([[28],
       [12]])

In [67]:
# 第一步：判断A是否有逆矩阵。行列式不为0说明存在逆矩阵，存在唯一解
np.linalg.det(A)

15.999999999999991

In [63]:
# 第二步：直接求结果
np.linalg.solve(A,B)

array([[1.],
       [1.]])

In [70]:
# 或者求出逆矩阵再算结果
np.dot(np.linalg.inv(A),B)

array([[1.],
       [1.]])